version: "3.8"
services:

  api-app:
    image: docker.io/bitnami/laravel:11
    ports:
      - '3002:8000'
    environment:
      - DB_HOST=db-mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_DATABASE=db_practica
    volumes:
      - .:/app
    depends_on:
      - db-mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - '9203:9000'
    depends_on:
      - api-app # O la dependencia que realmente necesite

  db-mysql:
    image: mysql:8.1.0
    ports:
      - '3003:3306'
    environment:
      MYSQL_DATABASE: db_practica
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - v-db-mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - '3004:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db-mysql
      PMA_PORT: 3306
    depends_on:
      - db-mysql

  composer:
    image: composer:2.7.6
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - api-app # O la dependencia que realmente necesite

volumes:
  v-db-mysql: